[%GROUP%]
  comment = Group public area
  path = /home/public/%GROUP%
  public = no
  writable = yes
  printable = no
  valid users = %GROUP_USERS%
  force group = users
  force create mode = 0664
  force directory mode = 0775
